// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20210410230343_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.VonageVideoAPIProjectCredential", b =>
                {
                    b.Property<int>("ApiKey")
                        .HasColumnType("int");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApiKey");

                    b.ToTable("VonageVideoAPIProjectCredentials");
                });

            modelBuilder.Entity("WebApplication.Models.VonageVideoAPISession", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ProjectApiKey")
                        .HasColumnType("int");

                    b.HasKey("SessionId");

                    b.HasIndex("ProjectApiKey");

                    b.ToTable("VonageVideoAPISessions");
                });

            modelBuilder.Entity("WebApplication.Models.VonageVideoAPISession", b =>
                {
                    b.HasOne("WebApplication.Models.VonageVideoAPIProjectCredential", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectApiKey");

                    b.Navigation("Project");
                });
#pragma warning restore 612, 618
        }
    }
}
